---
apiVersion: batch/v1
kind: "job"
metadata:
  name: "byowl-{{ item }}-{{ trunc_uuid }}"
  namespace: "{{ operator_namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
       app: byowl-{{ trunc_uuid }}
    spec:
      containers:
      - name: byowl
        command: ["/bin/sh", "-c"]
        args: ["{{ workload.commands }}"]
        image: "{{ workload.image }}"
        imagePullPolicy: Always
        imagePullSecrets:
            -name: abdasgupta-pull-secret
        wait: true
      restartPolicy: OnFailure
      serviceAccountName: benchmark-operator
